import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            width: "100%",
            background: "teal",
            fontSize: "50px",
            display: "flex",
            // gap:"10px",
            justifyContent: "center",
            alignItems: "center",
            listStyle:"none",
          }}
        >
          <Link href="/">
            <li style={{margin:"7px"}} >Home</li>
          </Link>
          <Link href="/posts">
          <li style={{margin:"7px"}} >posts</li>
          </Link>
          <Link href="/articles">
          <li style={{margin:"7px"}} >Articles</li>
          </Link>
        </nav>
        {children}
        <footer  style={{
            width: "100%",
            background: "teal",
            fontSize: "50px",
            display: "flex",
            // gap:"10px",
            justifyContent: "center",
            alignItems: "center",
            listStyle:"none",
          }}>
          <div>
            <ul>Home</ul>
            <ul>POSTS</ul>
          </div>
        </footer>
      </body>
    </html>
  );
}
